# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 8003:80